[error] java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 13
[error] 	at utils.data.MakeCSV$.$anonfun$new$5(MakeCSV.scala:44)
[error] 	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[error] 	at utils.data.MakeCSV$.$anonfun$new$1(MakeCSV.scala:43)
[error] 	at utils.data.MakeCSV$.$anonfun$new$1$adapted(MakeCSV.scala:23)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
[error] 	at utils.data.MakeCSV$.delayedEndpoint$utils$data$MakeCSV$1(MakeCSV.scala:23)
[error] 	at utils.data.MakeCSV$delayedInit$body.apply(MakeCSV.scala:11)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:42)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:42)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1(App.scala:98)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:98)
[error] 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
[error] 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
[error] 	at scala.App.main(App.scala:98)
[error] 	at scala.App.main$(App.scala:96)
[error] 	at utils.data.MakeCSV$.main(MakeCSV.scala:11)
[error] 	at utils.data.MakeCSV.main(MakeCSV.scala)
[error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[error] 	at sbt.Run.invokeMain(Run.scala:143)
[error] 	at sbt.Run.execute$1(Run.scala:93)
[error] 	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
[error] 	at sbt.Run$.executeSuccess(Run.scala:186)
[error] 	at sbt.Run.runWithLoader(Run.scala:120)
[error] 	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:1983)
[error] 	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1922)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at scala.util.Try$.apply(Try.scala:213)
[error] 	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (Compile / run) java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 13
